<?php
/**
 * Created by IntelliJ IDEA.
 * User: jasminsuljic
 * Date: 30/06/2018
 * Time: 13:35
 */

namespace backend\controllers;


use api\modules\v1\service\UserService;
use api\modules\v1\service\UserServiceImpl;
use yii\web\Controller;

class UserController extends Controller
{

    /**
     * @var UserService
     */
    private $service;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->service = new UserServiceImpl();
    }


    public function actionView($id)
    {
        return $this->service->getEnrolledUser($id);
    }

}