<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 30.6.2018.
 * Time: 13:00
 */

namespace api\modules\v1\controllers;


use api\components\ActiveController;
use api\modules\v1\service\EnrollmentService;
use api\modules\v1\service\EnrollmentServiceImpl;
use common\models\User;
use yii\base\InvalidConfigException;
use yii\web\HttpException;

/**
 * Class EnrollmentController
 * @package api\modules\v1\controllers
 */
class EnrollmentController extends ActiveController
{
    public $modelClass = User::class;

    /**
     * @var EnrollmentService
     */
    private $api;

    public function init()
    {
        try {
            parent::init();
        } catch (InvalidConfigException $e) {
        } // TODO: Change the autogenerated stub

        $this->api = new EnrollmentServiceImpl();
    }


    /**
     * @param $id
     * @param $type
     * @return array
     */
    public function actionStatus($id, $type)
    {
        return $this->api->enrollmentStatus($id, $type);
    }
}