<?php
/**
 * Created by PhpStorm.
 * User: User
 * Date: 30.6.2018.
 * Time: 13:03
 */

namespace api\modules\v1\controllers;


use api\components\ActiveController;
use api\modules\v1\service\UserService;
use api\modules\v1\service\UserServiceImpl;
use common\models\User;

/**
 * Class UserController
 * @package api\modules\v1\controllers
 */
class UserController extends ActiveController
{
    public $modelClass = User::class;

    /**
     * @var UserService
     */
    private $api;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api = new UserServiceImpl();
    }


    /**
     * @return array
     */
    public function actions()
    {
        $actions = parent::actions();
        unset($actions['view']);
        return $actions;
    }

    /**
     * @param $id
     * @return array
     */
    public function actionView($id)
    {
        return $this->api->getEnrolledUser($id);
    }
}